services:
  - type: web
    name: villain-vault
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && ./run-migrations.sh"
    startCommand: "gunicorn villainsproject.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        fromDatabase:
          name: villains
          property: connectionString
databases:
  - name: villains
    engine: postgres